development:
  adapter: mysql
  database: cytosite_dev
  username: root
  password: root

test:
  adapter: mysql
  database: cytosite_test
  username: root
  password: root

production:
  adapter: mysql
  database: cytosite_prod
  username: root
  password: root
