development:
  adapter: mysql
  database: cytosite_dev
  username: root
  password:
  host: localhost

test:
  adapter: mysql
  database: cytosite_test
  username: root
  password:
  host: localhost

production:
  adapter: mysql
  database: cytosite_prod
  username: root
  password: root
