#Creating default users
User.destroy_all
User.create!(:email => 'samik2803@gmail.com', :name => 'Samik Pal', :password => 'P@ssw0rd', :password_confirmation => 'P@ssw0rd', :role => 'admin')
User.create!(:email => 'toamitkumar@gmail.com', :name => 'Amit Kumar', :password => 'P@ssw0rd', :password_confirmation => 'P@ssw0rd', :role => 'admin')
User.create!(:email => 'asaqi@hotmail.com', :name => 'Anjali Saqi', :password => 'P@ssw0rd', :password_confirmation => 'P@ssw0rd', :role => 'admin')

#Creating categories
Category.destroy_all
exfol = Category.create(:name => "Exfoliative", :code => "exfoliative", :parent_id => nil, :level => "0", :sort_order => "1")
gyne = Category.create(:name => "Gynecological", :code => "gyne", :parent_id => exfol.id, :level => "1", :sort_order => "2")
neoplas = Category.create(:name => "Neo-plastic", :code => "neoplas", :parent_id => gyne.id, :level => "2", :sort_order => "3")
Category.create(:name => "Squamous", :code => "squamous", :parent_id => neoplas.id, :level => "3", :sort_order => "4")
Category.create(:name => "Glandular", :code => "glandular", :parent_id => neoplas.id, :level => "3", :sort_order => "5")
Category.create(:name => "Non neo-plastic", :code => "non_plastic", :parent_id => gyne.id, :level => "2", :sort_order => "6")
non_gyne = Category.create(:name => "Non Gynecological", :code => "non_gyne", :parent_id => exfol.id, :level => "1", :sort_order => "7")
Category.create(:name => "CSF", :code => "csf", :parent_id => non_gyne.id, :level => "2", :sort_order => "8")
Category.create(:name => "Fluids", :code => "fluids", :parent_id => non_gyne.id, :level => "2", :sort_order => "9")
Category.create(:name => "Gastrointestinal", :code => "gastric", :parent_id => non_gyne.id, :level => "2", :sort_order => "10")
Category.create(:name => "Respiratory", :code => "respiratory", :parent_id => non_gyne.id, :level => "2", :sort_order => "11")
Category.create(:name => "Urine", :code => "urine", :parent_id => non_gyne.id, :level => "2", :sort_order => "12")
needle = Category.create(:name => "Fine needle aspiration", :code => "needle", :parent_id => nil, :level => "0", :sort_order => "13")
Category.create(:name => "Bone and soft tissue", :code => "bone", :parent_id => needle.id, :level => "1", :sort_order => "14")
Category.create(:name => "Breast", :code => "breast", :parent_id => needle.id, :level => "1", :sort_order => "15")
Category.create(:name => "Gastrointestinal", :code => "needlegastric", :parent_id => needle.id, :level => "1", :sort_order => "16")
Category.create(:name => "Genitourinary", :code => "geni", :parent_id => needle.id, :level => "1", :sort_order => "17")
Category.create(:name => "Hematopoietic", :code => "hema", :parent_id => needle.id, :level => "1", :sort_order => "18")
Category.create(:name => "Liver", :code => "liver", :parent_id => needle.id, :level => "1", :sort_order => "19")
Category.create(:name => "Lung/ Thorax", :code => "lung", :parent_id => needle.id, :level => "1", :sort_order => "20")
Category.create(:name => "Pancreas", :code => "pancreas", :parent_id => needle.id, :level => "1", :sort_order => "21")
Category.create(:name => "Salivary Glands", :code => "salivary", :parent_id => needle.id, :level => "1", :sort_order => "22")
Category.create(:name => "Thyroid", :code => "thyroid", :parent_id => needle.id, :level => "1", :sort_order => "23")